<h1 align='center' >Numpy and pandas understanding</h1>


In [1]:
print("hello ashim")

hello ashim


In [2]:
list_of_numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sum=0
for n in list_of_numbers:
    sum=sum+n
print(sum)

55


<h3 align='center'>Installing jupiter noteboook</h3>

In [5]:
# To provide cmd command start with !
!python install numpy

python: can't open file 'a:\\Trainings\\hackedemia\\python\\Numpy\\install': [Errno 2] No such file or directory


<h3 align='centre' >Basics</h3>

In [6]:
import numpy as np

array_of_numbers=np.array([1,2,3,4,5])
print(array_of_numbers,type(array_of_numbers))
print(array_of_numbers.sum())
print(array_of_numbers.mean())
print(array_of_numbers.std())
print(array_of_numbers.max())
print(array_of_numbers.cumsum())

[1 2 3 4 5] <class 'numpy.ndarray'>
15
3.0
1.4142135623730951
5
[ 1  3  6 10 15]


In [7]:
matrix=np.array(([1,2],[3,4]))
matrix1=np.array(([5,6],[7,8]))
print(np.linalg.det(matrix))
trans=matrix1.T
print(trans)
print(np.dot(matrix,matrix1))
print(np.linalg.inv(matrix))
print(np.linalg.solve(matrix,matrix1))
list=[]
row=int(input("enter number of rows\n"))
column=int(input("enter number of rows\n"))
for i in range(row):
    list.append([])
    for j in range(column):
        list[i].append(int(input()))
print(np.array(list))


[[-3. -4.]
 [ 4.  5.]]


In [9]:
# print(np.linalg.solve(matrix,matrix1))
print(np.exp(2))
print(np.sqrt(2))


7.38905609893065
1.4142135623730951
